## 17.5 Letters and Numbers: Given an array with letters and numbers, find the longest subarray with an equal number of letters and numbers.

For this example, we will just substitute '+' and '-'



In [127]:
import numpy as np

testarray1 = ['+', '-', '+', '+', '+', '-', '-', '-', '+', '-', '+', '+', '-', '-', '+', '+', '+', '+', '+', '+', '+']
#testarray1 = ['+', '-', '+', '+', '+', '-', '-', '-', '+', '-', '+', '+', '-', '-', '+', '+', '+', '+', '-', '-', '-', '-']

#testarray1 = ['+', '-', '+', '-']

In [128]:
def plusminusNOT(i):
    if i=='+':
        return 1
    elif i=='-':
        return -1
    else:
        return 0
    
def plus_to_nparray(list):
    return np.array([plusminusNOT(i) for i in list])
    

In [129]:
array = plus_to_nparray(testarray1)

## Brute force: start with the largest string and then just see if the sum is zero.  Once you find a sum of zero, return that and quit.

In [130]:
def find_longest_subarray(array):
    longest_length = 0
    for l in range(-1+len(array),-1,-1):
        if (longest_length!=0)&(l<=longest_length): # Break if there's no chance to find a longer substring than
            break                                   # we have already found.
        for i in range(0,l):
            if (array[i:l+1].sum()==0) & ((l-i+1)>longest_length):
                longest_length = l-i+1
                longest_array  = array[i:l+1]
    return('longest subarray:',longest_array)

In [131]:
print(find_longest_subarray(array))

('longest subarray:', array([-1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1, -1, -1,  1]))


## Better implementation with cumulative sum

In [132]:
array.cumsum()

array([1, 0, 1, 2, 3, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7])

In [133]:
cs = np.insert(array.cumsum(),0,0)
print(cs)

[0 1 0 1 2 3 2 1 0 1 0 1 2 1 0 1 2 3 4 5 6 7]


In [134]:
array[0:22].sum()

7

In [135]:
def find_longest_subarray_cumsum(array):
    from collections import defaultdict
    cs = np.insert(array.cumsum(),0,0)
    # find indices of furthest apart matching numbers in cs
    # go through the array and update a dict with the matching points (a list) of positions matching
    # specific cumsums
    csmap = defaultdict(list)
    for count,item in enumerate(cs):
        csmap[item].append(count)
    max_span = 0
    for key in csmap:
        span = csmap[key][-1] - csmap[key][0]
        if span > max_span:
            max_span = span
            span_beg = csmap[key][0]
            span_end = csmap[key][-1]
            

        
    return(array[span_beg:span_end])
    

In [136]:
x=find_longest_subarray_cumsum(array)
x

array([ 1, -1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1, -1, -1])

## WOOT!